substitutions:
  devicename: ci
  friendly_name: $devicename

external_components:
  refresh: always
  source: ../components

esphome:
  name: $devicename

button:
  - platform: restart
    name: $friendly_name Restart
    entity_category: config
  - platform: template
    name: $friendly_name Recalibrate
    on_press:
      - lambda: id(roode_platform)->recalibration();
    entity_category: config

number:
  - platform: roode
    people_counter:
      name: $friendly_name people counter

binary_sensor:
  - platform: roode
    presence:
      name: $friendly_name Presence
    zones:
      entry:
        presence:
          name: $friendly_name Entry Presence
      exit:
        presence:
          name: $friendly_name Exit Presence

sensor:
  - platform: roode
    zones:
      entry:
        distance:
          name: $friendly_name Entry Distance
          filters:
            - delta: 100
      exit:
        distance:
          name: $friendly_name Exit Distance
          filters:
            - delta: 100
    max_threshold_entry:
      name: $friendly_name max zone 0
    max_threshold_exit:
      name: $friendly_name max zone 1
    min_threshold_entry:
      name: $friendly_name min zone 0
    min_threshold_exit:
      name: $friendly_name min zone 1
    roi_height_entry:
      name: $friendly_name ROI height zone 0
    roi_width_entry:
      name: $friendly_name ROI width zone 0
    roi_height_exit:
      name: $friendly_name ROI height zone 1
    roi_width_exit:
      name: $friendly_name ROI width zone 1
    sensor_status:
      name: Sensor Status

text_sensor:
  - platform: roode
    version:
      name: $friendly_name version
  - platform: roode
    entry_exit_event:
      name: $friendly_name last direction
